title_primary: "活版印字" # the bigger text
title_secondary: "Typography" # the smaller text
keywords:

twitter: # user_name
rss: atom.xml
weibo: # user_id/permanent_name
instagram: # user_name
github: # user_name

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show current page number and total page count beyond page link.
showPageCount: true

# Set true to show category or tags behind post title.
showCategories: true
showTag: true

# Choose theme style
themeStyle: dark # light, dark